version: "3.8"

services:
  artemis:
    image: apache/activemq-artemis:2.33.0
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      ARTEMIS_USER: quarkus
      ARTEMIS_PASSWORD: quarkus